runtime: python39

env: flex

entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 10
  cpu_utilization:
    target_utilization: 0.5

instance_class: f2