steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'  # Specify the path to your app.yaml file
    timeout: '1600s'  # Set a timeout for the build process
